# Generated by Django 2.1.5 on 2019-01-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_data', '0002_auto_20190111_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='match_id',
            new_name='match',
        ),
    ]
